# fly.toml app configuration file generated for activitiesapp on 2023-06-24T16:57:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "activitiesapp"
primary_region = "lhr"

[build]
  image = "grsse/activities:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "621877894579812"
  CloudinarySettings__CloudName = "kw9xdfo024q"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
